### PR TITLE
First build

### PR DESCRIPTION
**Pull request by dNadiia**

### CODE REVIEW

**Comment by alexhansonsmith** [comment]
HI @dNadiia - please could you email us on enquiries@inploi.me so we can discuss the test. Thanks - inploi

**Comment by dNadiia** [comment]
@chrismackie28 how may I create new branch at your repo?
I can't push exactly to new branch as haven't access.
Also I can't create pull request to branch of your repo which not exists.
Once you'll create branch with my nickname than I'll be able to do this.
Thanks!

**Comment by chrismackie28** [comment]
@dNadiia If you create one on your fork and then do the pull request

**Comment by dNadiia** [comment]
screen shot 2017-07-17 at 17 22 07

So I can't pull to new branch. Only master.

**Pull request closed without merging**
